FROM azul/zulu-openjdk:17-latest AS builder

RUN apt-get update && apt-get install -y maven

VOLUME [ "/root/.m2", "/target" ]

WORKDIR /jmc
COPY core core/
COPY application application/
COPY configuration configuration/
COPY license license/
COPY releng releng/
COPY pom.xml ./
COPY docker/docker-toolchains.xml .mvn/toolchains.xml
RUN grep -rl localhost:8080 releng | xargs sed -i s/localhost:8080/p2:8080/
ENV MAVEN_OPTS="-Xmx1G"

CMD mvn clean install --file core/pom.xml --toolchains .mvn/toolchains.xml \
  && mvn package --toolchains .mvn/toolchains.xml \
  && cp -a /jmc/target/* /target
