name: Test formatting

on: [push, pull_request]

jobs:
  linux:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: ./scripts/formatting.sh

  mac:
    runs-on: 'macOS-latest'
    steps:
    - uses: actions/checkout@v1
    - name: Install Mercurial
      run: brew install mercurial
    - name: Build and test
      run: ./scripts/formatting.sh

  win:
    runs-on: 'windows-latest'
    steps:
    - uses: actions/checkout@v1
    - name: Build and test
      run: ./scripts/formatting.bat
      shell: cmd
